services:
    api:
        container_name: main_app
        build: .
        command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
        environment:
            POSTGRESQL_DB_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
        depends_on:
            - db
        ports:
            - "8000:8000"
        volumes:
            - src:/app/src
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
    celery_worker:
        container_name: celery_worker
        build: .
        command: celery -A src.celery_tasks:celery worker -l info
        environment:
            - CELERY_BROKER_URL=${CELERY_BROKER_URL}
            - CELERY_BACKEND_URL=${CELERY_BACKEND_URL}
        depends_on:
            - api
            - redis
        volumes:
            - src:/app/src
    flower:
        container_name: flower
        build: .
        command: celery -A src.celery_tasks:celery flower --port=5555
        ports:
            - "5555:5555"
        environment:
            - CELERY_BROKER_URL=${CELERY_BROKER_URL}
            - CELERY_BACKEND_URL=${CELERY_BACKEND_URL}
        depends_on:
            - api
            - redis
            - celery_worker
        volumes:
            - src:/app/src
    db:
        image: postgres:14
        container_name: postgres_db
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  src: